### ISSUE TITLE
The vscodium installed by flatpak is freezing.

### ISSUE THREAD

**Issue by xgrind** [ManuelGil/vscode-codeigniter4-pack#1]
The vscodium installed by flatpak is freezing. But it doesn't freeze via .rpm or dnf repository.
I tested another extension package for CI4, and it didn't freeze.

**Comment by ManuelGil** [comment]
It seems to be a bug in the way Codium installs extensions.

This extension is a package of 26 extensions while the other CodeIgniter packages only have 4 extensions.

I recommend you to install the extensions individually to avoid issues.

**Comment by xgrind** [comment]
I just did a new test and vscodium in flatpak crashed without any extension, just opening a project in .php.
So it's not a problem with the extension. I'm closing the bug.
